### ISSUE TITLE
Image Loading

### ISSUE THREAD

**Issue by fatuma-tahalil** [fatuma-tahalil/Silver-Robotics-Web-Design#2]
The large images changed to JPEG won't load. Smaller ones such as the Instagram icon, and robot photo will.
![image](https://github.com/user-attachments/assets/fb5e9d19-5b70-425c-afb3-b9c714d0c66e)

**Comment by gilwiljam** [comment]
I believe this is an issue with the server not correctly syncing the Git repo. 
When I cloned the repo, it runs with all images completely fine in the localhost. I will try and re-upload the images to the Github. Also the image on the Robots page works fine, for whatever reason. 

It also seems to work if you outsource the image (e.g. not storing it on the server, grabbing it from the GitHub API or something along those lines), although that is a worse solution than just fixing it and storing it on the server. 

The first thing we should do is go onto the FTP server and verify the names/locations of all the images - they may not be properly synced to the Git repo.

**Comment by gilwiljam** [comment]
Fixed by re-uploading the files to the FTP (they had not been updated and were still using the PNG format, which caused a 404 error). I still had access to it on my laptop. The website should work normally now and the images return a 200. 

Please note, for any further issues, that uploading multiple files at a time to the GitHub will sometimes bug the sync, and cause it to not upload the files.
